In [ ]:
import torch

In [7]:
# Tensor a partir de lista
t1 = torch.tensor([1.0, 2.0, 3.0])
print(t1)

tensor([1., 2., 3.])


In [8]:
# Tensor com valores aleatórios
t2 = torch.randn(2, 3)  # 2 linhas, 3 colunas
print(t2)

tensor([[ 0.7672,  0.0464,  0.4477],
        [-0.8603,  1.2338,  2.5839]])


In [9]:
# Tensor com todos os zeros
z = torch.zeros(4, 4)
print(z)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [10]:
# Tensor preenchido com 1s
o = torch.ones(2,2)
print(o)

tensor([[1., 1.],
        [1., 1.]])


In [16]:
# Operações Matemáticas com Tensores (similar ao NumPy)
a = torch.tensor([1.0, 2.0])
b = torch.tensor([3.0, 4.0])
c = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

# Soma
print(a + c)

# Multiplicação (elemento a elemento)
print(a * b)

# Produto Escalar
print(a @ b)

tensor([[ 6.,  8.],
        [ 8., 10.]])
tensor([3., 8.])
tensor(11.)


### Funções

In [ ]:
def sum_tensor(a, b): # Definir função de soma
    # Soma dois tensores
    return a + b

def set_device(): # Definir dispositivo para tensor
    # Verifica se CUDA está disponível e define o dispositivo apropriado
    # Se CUDA não estiver disponível, usa CPU
    return torch.device('cuda' if torch.cuda.is_available() else 'cpu')

def reshape_tensor(t): # Redimensionar tensor
    print(t.shape) # Imprime a forma original do tensor
    print(t.ndim) # Imprime o número de dimensões do tensor

def broadcast_tensor(a, b): # Broadcast de tensores
    # Realiza broadcast entre dois tensores e retorna o resultado
    return a + b

def autograd_tensor(): # Demonstração do autograd do PyTorch
    # Cria um tensor com gradientes habilitados e calcula a derivada de uma função polinomial com relação a esse tensor
    x = torch.tensor(2.0, requires_grad=True)
    y = x ** 4 + x ** 3 + 3 * x ** 2 + 6 * x + 1
    y.backward()
    print(x.grad)

In [17]:
print(set_device()) # Imprime o dispositivo atual

cpu
